# -*- coding: utf-8 -*-
"""plots.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kRlMN1y5Ok7qVtXibh1NzLPv3grrVtSB
"""

import matplotlib.pyplot as plt

def plot_model_history(train_acc, val_acc, train_loss, val_loss):
    fig, axs = plt.subplots(1,2,figsize=(15,5))
    # summarize history for accuracy
    axs[0].plot(range(1,25), train_acc)
    axs[0].plot(range(1,25), val_acc)
    axs[0].set_title('Model Accuracy')
    axs[0].set_ylabel('Accuracy')
    axs[0].set_xlabel('Epoch')
    axs[0].set_xticks(np.arange(1,25),(25)/10)
    axs[0].legend(['train', 'val'], loc='best')

    # summarize history for loss
    axs[1].plot(range(1,25), train_loss)
    axs[1].plot(range(1,25), val_loss)
    axs[1].set_title('Model Loss')
    axs[1].set_ylabel('Loss')
    axs[1].set_xlabel('Epoch')
    axs[1].set_xticks(np.arange(1,25),(25)/10)
    axs[1].legend(['train', 'val'], loc='best')
    plt.show()